### ISSUE TITLE
Multiple output folders

### ISSUE THREAD

**Issue by Jimshark** [ColiseoSoftware/hypervbackup#6]
Would it be difficult to add Multiple output folder destinations:
-o "\Nas1\vmbackup", "\Nas2\vmbackup"
You have 2 NAS and you just want to make 2 copies of the VM backups.
But may be it has to be managed on a script that uses hypervbackup ?
Cheers, Jim

**Comment by pablopioli** [comment]
It would be difficult, the program is built around the concept of one output, but it could be done.
The real problem is that while you do the second copy you have a VSS snapshot open, as a full backup can take a long time this could put a lot of stress on the server.
I would copy from the first NAS to the second NAS after HyperVBackup has finished using a custom script.

**Comment by Jimshark** [comment]
Hi Pablo, thanks for your advises. I understand. I did 3 HyperVBackup jobs with 3 different destinations. As it's backuping quite fast i'm able to do the 3 at night. I will test a robocopy from one NAS to another to compare the speed. The v2.3 is still working fine. Kind regards, JM

**Comment by pablopioli** [comment]
Copying from the NAS should be orders or magnitud faster. NAS are designed for copy operations, while compress is a heavy user of the processor.
I think implementing this will be more a trouble than a help.
